### ISSUE TITLE
update element of array

### ISSUE THREAD

**Issue by wizard580** [mikefarah/yaml#12]
This is not an issue, but very important task for me:
let.s assume I have following yaml:
```
test:
  a:
    - name: name1
      value: 1
    - name: name2
      value: 2
```
and I need to update only **value** where name == name1

Is it possible with this tool?
