### ISSUE TITLE
no matches found: write_files[0].path [cloud-config.yml]

### ISSUE THREAD

**Issue by Jacek-Kurasiewicz** [mikefarah/yaml#14]
I'm trying to read a value of write_files[0].content and then set another value to the same path.

It doesn't work with write_files[0].path
```bash
$ yaml r templates/coreos-install-cloud-config/skeleton.yml \                     
        write_files[0].path 
bash: no matches found: write_files[0].path
```
Doesn't work with write_files[0]
```bash
yaml r templates/coreos-install-cloud-config/skeleton.yml \
        write_files[0]
bash: no matches found: write_files[0]
```
But if I request the full value of write_files the I get what I asked for:
```bash
yaml r templates/coreos-install-cloud-config/skeleton.yml \
        write_files        
- path: /root/process-cloud-config.sh
  permissions: "0755"
  owner: root
  content: null
- path: /root/cloud-config.yml
  permissions: "0644"
  owner: root
  content: null
```

Here is the file I'm processing:
```yaml
write_files:
  - path: /root/process-cloud-config.sh
    permissions: "0755"
    owner: root
    content: 

  - path: /root/cloud-config.yml
    permissions: "0644"
    owner: root
    content:
```

Can you advise how to handle my case with yaml tool?
