### ISSUE TITLE
Dots in variable name

### ISSUE THREAD

**Issue by cdaguerre** [mikefarah/yaml#22]
This script doesnt work for:
```yaml
# parameters.yml
parameters:
  database.name: app
```

```sh
$ yaml read parameters.yml parameters.database.name
null
```
I think this is valid yaml.
Am I missing something?
