### ISSUE TITLE
Can't process valid yaml

### ISSUE THREAD

**Issue by samiralajmovic** [mikefarah/yaml#23]
Running command `yaml read test.yaml gather_facts` results in output **null**, expected result is **false**. Culprit is the `-` in-front of **become**, which is valid yaml. If I remove it, it works but it should obviously work with it as well.

```yaml
---
- become: true
  gather_facts: false
  hosts: lalaland
  name: "Apply smth"
  roles:
    - lala
    - land
  serial: 1
```
