### ISSUE TITLE
Incorrect parsing of file with nested key

### ISSUE THREAD

**Issue by jmreicha** [mikefarah/yaml#4]
Given the following example:

```
version: '2'
services:
  test:
    image: ubuntu:14.04
    stdin_open: true
    tty: true
```

When I try to update the `image` key, using both the in place and write to stdout command:

```
yaml w docker-compose.yml services.test.image nginx:master
yaml w -i docker-compose.yml services.test.image nginx:master
```

I get unexpected output:

```
services:
  test:
    image: nginx:master
    stdin_open: true
    tty: true
version: "2"
```
