### ISSUE TITLE
Single quotes vs Double quotes

### ISSUE THREAD

**Issue by mikefarah** [mikefarah/yaml#6]
When updating a Yaml file, the original quotes are not maintained, e.g.  'version' originally has single quotes, but this ends up with double quotes.

```
version: '2'
services:
  test:
    image: ubuntu:14.04
    stdin_open: true
    tty: true
```
yaml w docker-compose.yml services.test.image nginx:master
```
services:
  test:
    image: nginx:master
    stdin_open: true
    tty: true
version: "2"
```
